name: EMD_py
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=20.3.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - catalogue=1.0.0
  - category_encoders=2.2.2
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.3.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cymem=2.0.4
  - cython-blis=0.4.1
  - dbus=1.13.18
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - joblib=1.0.0
  - jpeg=9b
  - jsonschema=3.0.2
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - murmurhash=1.0.5
  - ncurses=6.2
  - ninja=1.10.2
  - nltk=3.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.2.1
  - patsy=0.5.1
  - pcre=8.44
  - pillow=8.1.0
  - pip=20.3.3
  - plac=1.1.0
  - preshed=3.0.2
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.0
  - pytz=2020.5
  - qt=5.9.7
  - readline=8.1
  - regex=2020.11.13
  - requests=2.25.1
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - spacy=2.3.5
  - sqlite=3.33.0
  - srsly=1.0.5
  - statsmodels=0.12.1
  - thinc=7.4.5
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.7.0
  - torchtext=0.8.0
  - torchvision=0.8.1
  - tornado=6.1
  - tqdm=4.56.0
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wasabi=0.8.1
  - wheel=0.36.2
  - xz=5.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
